### ISSUE TITLE
OSX GCS USB failure

### ISSUE THREAD

**Issue by peabody124** [TauLabs/TauLabs#807]
I got this warning and this BT.  It opens the connection but doesn't do anything.
```
[11:48:42.470] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.470] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.470] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.470] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.470] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.471] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.471] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.471] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.471] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.471] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.471] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.471] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.472] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.472] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.472] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.472] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.472] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.472] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.473] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.473] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.473] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.473] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.473] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.473] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.474] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.474] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
[11:48:42.474] [Warning] QMutex::lock(): cv wait failure: Invalid argument                         qwarning
^C
Program received signal SIGINT, Interrupt.
0x000000010092e84b in QTextCursor::insertBlock ()
(gdb) bt
#0  0x000000010092e84b in QTextCursor::insertBlock ()
#1  0x00000001008bb4d1 in QTextControlPrivate::append ()
#2  0x0000000100ae333c in QTextEdit::append ()
#3  0x000000010e41f931 in DebugGadgetWidget::dbgMsg (this=0x119f06990, level=@0x7fff5fbfc8c0, msgs=@0x113d15530) at debuggadgetwidget.cpp:62
#4  0x000000010e421d8d in DebugGadgetWidget::qt_static_metacall (_o=0x119f06990, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7fff5fbfc770) at moc_debuggadgetwidget.cpp:55
#5  0x00000001003861ee in QMetaObject::activate ()
#6  0x000000010e421468 in debugengine::dbgMsg (this=0x119f05300, _t1=@0x7fff5fbfc8c0, _t2=@0x113d15530) at moc_debugengine.cpp:111
#7  0x000000010e41cbf9 in debugengine::writeToStdOut (this=0x119f05300, level=@0x7fff5fbfc8c0, msgs=@0x113d15530) at debugengine.cpp:12
#8  0x000000010e41cbc8 in non-virtual thunk to debugengine::writeToStdOut(QString const&, QList<QVariant> const&) () at debugengine.cpp:4
#9  0x000000010de5566f in QxtBasicSTDLoggerEngine::writeFormatted (this=0x119f05310, level=QxtLogger::WarningLevel, msgs=@0x113d15530) at qxtbasicstdloggerengine.cpp:156
#10 0x000000010de14170 in QxtLoggerPrivate::log (this=0x10259f5a0, level=QxtLogger::WarningLevel, msgList=@0x113d15530) at qxtlogger.cpp:164
#11 0x000000010de70d6d in QxtLoggerPrivate::qt_static_metacall (_o=0x10259f5a0, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x113d154f0) at moc_qxtlogger_p.cpp:50
#12 0x0000000100382711 in QObject::event ()
#13 0x00000001006849ed in QApplicationPrivate::notify_helper ()
#14 0x000000010068b064 in QApplication::notify ()
#15 0x000000010036e20c in QCoreApplication::notifyInternal ()
#16 0x000000010036f620 in QCoreApplicationPrivate::sendPostedEvents ()
#17 0x00007fff8d14bb31 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#18 0x00007fff8d14b455 in __CFRunLoopDoSources0 ()
#19 0x00007fff8d16e7f5 in __CFRunLoopRun ()
#20 0x00007fff8d16e0e2 in CFRunLoopRunSpecific ()
#21 0x00007fff8cd6eeb4 in RunCurrentEventLoopInMode ()
#22 0x00007fff8cd6ec52 in ReceiveNextEventCommon ()
#23 0x00007fff8cd6eae3 in BlockUntilNextEventMatchingListInMode ()
#24 0x00007fff8846a563 in _DPSNextEvent ()
#25 0x00007fff88469e22 in -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] ()
#26 0x00007fff884611d3 in -[NSApplication run] ()
#27 0x000000010063da80 in QEventDispatcherMac::processEvents ()
#28 0x000000010036d114 in QEventLoop::processEvents ()
#29 0x000000010036d4c4 in QEventLoop::exec ()
#30 0x000000010036fbac in QCoreApplication::exec ()
#31 0x000000010000e483 in main (argc=1, argv=0x7fff5fbff9f0) at main.cpp:387
(gdb) thread apply all bt

Thread 31 (process 65399):
#0  0x00007fff864f8686 in mach_msg_trap ()
#1  0x00007fff864f7c42 in mach_msg ()
#2  0x00007fff877cdfaf in io_connect_method ()
#3  0x00007fff8778149e in IOConnectCallMethod ()
#4  0x000000011075966c in IOHIDDeviceClass::setReport ()
#5  0x00007fff877a0840 in IOHIDDeviceSetReport ()
#6  0x000000011010b45a in Sender::run (this=0x108133cf0) at pjrc_rawhid_mac.cpp:224
#7  0x0000000100253f74 in QThreadPrivate::start ()
#8  0x00007fff86e387a2 in _pthread_start ()
#9  0x00007fff86e251e1 in thread_start ()

Thread 30 (process 65399):
#0  0x00007fff864f947f in mach_port_deallocate ()
#1  0x00007fff864f807f in mach_msg_destroy_port ()
#2  0x00007fff864f7ef6 in mach_msg_destroy ()
#3  0x00007fff8d185dad in CFRunLoopWakeUp ()
#4  0x000000010036ecb0 in QCoreApplication::postEvent ()
#5  0x0000000100377ee0 in QMetaMethod::invoke ()
#6  0x000000010037a1cc in QMetaObject::invokeMethod ()
#7  0x000000010ddf9f3c in QMetaObject::invokeMethod (obj=0x10259f5a0, member=0x10de9c698 "log", type=Qt::AutoConnection, val0={_data = 0x107faf4d4, _name = 0x10de9c65f "QxtLogger::LogLevel"}, val1={_data = 0x107faf528, _name = 0x10de9c688 "QList<QVariant>"}, val2={_data = 0x0, _name = 0x0}, val3={_data = 0x0, _name = 0x0}, val4={_data = 0x0, _name = 0x0}, val5={_data = 0x0, _name = 0x0}, val6={_data = 0x0, _name = 0x0}, val7={_data = 0x0, _name = 0x0}, val8={_data = 0x0, _name = 0x0}, val9={_data = 0x0, _name = 0x0}) at qobjectdefs.h:418
#8  0x000000010de193a4 in QxtLogger::log (this=0x10deca990, level=QxtLogger::WarningLevel, args=@0x107faf528) at qxtlogger.cpp:547
#9  0x000000010de194df in QxtLogger::warning (this=0x10deca990, args=@0x107faf528) at qxtlogger.cpp:489
#10 0x000000010de1b0d4 in QxtLogger::warning (this=0x10deca990, message=@0x107faf810, msg1=@0x107faf800, msg2=@0x107faf7f0, msg3=@0x107faf7e0, msg4=@0x107faf7d0, msg5=@0x107faf7c0, msg6=@0x107faf7b0, msg7=@0x107faf7a0, msg8=@0x107faf790, msg9=@0x107faf780) at qxtlogger.cpp:347
#11 0x000000010de178e3 in QxtLoggerMessageHandler (type=QtWarningMsg, msg=0x1563026f8 "QMutex::lock(): cv wait failure: Invalid argument") at qxtlogger.cpp:565
#12 0x0000000100248ca1 in qt_message_output ()
#13 0x0000000100248ed7 in qt_message ()
#14 0x000000010024925a in qWarning ()
#15 0x0000000100253116 in report_error ()
#16 0x0000000100253358 in QMutexPrivate::wait ()
#17 0x000000010024e938 in QMutex::lock ()
#18 0x0000000100254368 in QThreadPrivate::finish ()
#19 0x0000000100253f83 in QThreadPrivate::start ()
#20 0x00007fff86e387a2 in _pthread_start ()
#21 0x00007fff86e251e1 in thread_start ()

Thread 29 (process 65399):
#0  0x00007fff864fa6d6 in __workq_kernreturn ()
#1  0x00007fff86e3af4c in _pthread_workq_return ()
#2  0x00007fff86e3ad13 in _pthread_wqthread ()
#3  0x00007fff86e251d1 in start_wqthread ()

Thread 13 (process 65399):
#0  0x00007fff864fa322 in select$DARWIN_EXTSN ()
#1  0x000000010039f585 in qt_safe_select ()
#2  0x00000001003a2f45 in QEventDispatcherUNIXPrivate::doSelect ()
#3  0x00000001003a38b2 in QEventDispatcherUNIX::processEvents ()
#4  0x000000010036d114 in QEventLoop::processEvents ()
#5  0x000000010036d4c4 in QEventLoop::exec ()
#6  0x0000000100251358 in QThread::exec ()
#7  0x0000000100253f74 in QThreadPrivate::start ()
#8  0x00007fff86e387a2 in _pthread_start ()
#9  0x00007fff86e251e1 in thread_start ()

Thread 12 (process 65399):
#0  0x00007fff864fa322 in select$DARWIN_EXTSN ()
#1  0x000000010039f585 in qt_safe_select ()
#2  0x00000001003a2f45 in QEventDispatcherUNIXPrivate::doSelect ()
#3  0x00000001003a38b2 in QEventDispatcherUNIX::processEvents ()
#4  0x000000010036d114 in QEventLoop::processEvents ()
#5  0x000000010036d4c4 in QEventLoop::exec ()
#6  0x0000000100251358 in QThread::exec ()
#7  0x0000000100253f74 in QThreadPrivate::start ()
#8  0x00007fff86e387a2 in _pthread_start ()
#9  0x00007fff86e251e1 in thread_start ()

Thread 11 (process 65399):
#0  0x00007fff864fa322 in select$DARWIN_EXTSN ()
#1  0x000000010039f585 in qt_safe_select ()
#2  0x00000001003a2f45 in QEventDispatcherUNIXPrivate::doSelect ()
#3  0x00000001003a38b2 in QEventDispatcherUNIX::processEvents ()
#4  0x000000010036d114 in QEventLoop::processEvents ()
#5  0x000000010036d4c4 in QEventLoop::exec ()
#6  0x0000000100251358 in QThread::exec ()
#7  0x00000001014fbc07 in QDeclarativeXmlQueryEngine::run ()
#8  0x0000000100253f74 in QThreadPrivate::start ()
#9  0x00007fff86e387a2 in _pthread_start ()
#10 0x00007fff86e251e1 in thread_start ()

Thread 10 (process 65399):
#0  0x00007fff864fa0fa in __psynch_cvwait ()
#1  0x00007fff86e3cfe9 in _pthread_cond_wait ()
#2  0x0000000101ae49d6 in QTWTF::TCMalloc_PageHeap::scavengerThread ()
#3  0x0000000101ae4a19 in QTWTF::TCMalloc_PageHeap::runScavengerThread ()
#4  0x00007fff86e387a2 in _pthread_start ()
#5  0x00007fff86e251e1 in thread_start ()

Thread 9 (process 65399):
#0  0x00007fff864fa0fa in __psynch_cvwait ()
#1  0x00007fff86e3cfe9 in _pthread_cond_wait ()
#2  0x0000000100253673 in thread_sleep ()
#3  0x00000001002537d3 in QThread::msleep ()
#4  0x00000001101304f9 in SerialEnumerationThread::run (this=0x10846aa40) at serialplugin.cpp:80
#5  0x0000000100253f74 in QThreadPrivate::start ()
#6  0x00007fff86e387a2 in _pthread_start ()
#7  0x00007fff86e251e1 in thread_start ()

Thread 8 (process 65399):
#0  0x00007fff864fa322 in select$DARWIN_EXTSN ()
#1  0x000000010039f585 in qt_safe_select ()
#2  0x00000001003a2f45 in QEventDispatcherUNIXPrivate::doSelect ()
#3  0x00000001003a38b2 in QEventDispatcherUNIX::processEvents ()
#4  0x000000010036d114 in QEventLoop::processEvents ()
#5  0x000000010036d4c4 in QEventLoop::exec ()
#6  0x0000000100251358 in QThread::exec ()
#7  0x0000000100253f74 in QThreadPrivate::start ()
#8  0x00007fff86e387a2 in _pthread_start ()
#9  0x00007fff86e251e1 in thread_start ()

Thread 7 (process 65399):
#0  0x00007fff864fa322 in select$DARWIN_EXTSN ()
#1  0x000000010039f585 in qt_safe_select ()
#2  0x00000001003a2f45 in QEventDispatcherUNIXPrivate::doSelect ()
#3  0x00000001003a38b2 in QEventDispatcherUNIX::processEvents ()
#4  0x000000010036d114 in QEventLoop::processEvents ()
#5  0x000000010036d4c4 in QEventLoop::exec ()
#6  0x0000000100251358 in QThread::exec ()
#7  0x0000000100253f74 in QThreadPrivate::start ()
#8  0x00007fff86e387a2 in _pthread_start ()
#9  0x00007fff86e251e1 in thread_start ()

Thread 6 (process 65399):
#0  0x00007fff864fa322 in select$DARWIN_EXTSN ()
#1  0x00007fff8d1adf46 in __CFSocketManager ()
#2  0x00007fff86e387a2 in _pthread_start ()
#3  0x00007fff86e251e1 in thread_start ()

Thread 2 (process 65399):
#0  0x00007fff864fad16 in kevent ()
#1  0x00007fff8f9fddea in _dispatch_mgr_invoke ()
#2  0x00007fff8f9fd9ee in _dispatch_mgr_thread ()

Thread 1 (process 65399):
#0  0x000000010092e84b in QTextCursor::insertBlock ()
#1  0x00000001008bb4d1 in QTextControlPrivate::append ()
#2  0x0000000100ae333c in QTextEdit::append ()
#3  0x000000010e41f931 in DebugGadgetWidget::dbgMsg (this=0x119f06990, level=@0x7fff5fbfc8c0, msgs=@0x113d15530) at debuggadgetwidget.cpp:62
#4  0x000000010e421d8d in DebugGadgetWidget::qt_static_metacall (_o=0x119f06990, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7fff5fbfc770) at moc_debuggadgetwidget.cpp:55
#5  0x00000001003861ee in QMetaObject::activate ()
#6  0x000000010e421468 in debugengine::dbgMsg (this=0x119f05300, _t1=@0x7fff5fbfc8c0, _t2=@0x113d15530) at moc_debugengine.cpp:111
#7  0x000000010e41cbf9 in debugengine::writeToStdOut (this=0x119f05300, level=@0x7fff5fbfc8c0, msgs=@0x113d15530) at debugengine.cpp:12
#8  0x000000010e41cbc8 in non-virtual thunk to debugengine::writeToStdOut(QString const&, QList<QVariant> const&) () at debugengine.cpp:4
#9  0x000000010de5566f in QxtBasicSTDLoggerEngine::writeFormatted (this=0x119f05310, level=QxtLogger::WarningLevel, msgs=@0x113d15530) at qxtbasicstdloggerengine.cpp:156
#10 0x000000010de14170 in QxtLoggerPrivate::log (this=0x10259f5a0, level=QxtLogger::WarningLevel, msgList=@0x113d15530) at qxtlogger.cpp:164
#11 0x000000010de70d6d in QxtLoggerPrivate::qt_static_metacall (_o=0x10259f5a0, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x113d154f0) at moc_qxtlogger_p.cpp:50
#12 0x0000000100382711 in QObject::event ()
#13 0x00000001006849ed in QApplicationPrivate::notify_helper ()
#14 0x000000010068b064 in QApplication::notify ()
#15 0x000000010036e20c in QCoreApplication::notifyInternal ()
#16 0x000000010036f620 in QCoreApplicationPrivate::sendPostedEvents ()
#17 0x00007fff8d14bb31 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#18 0x00007fff8d14b455 in __CFRunLoopDoSources0 ()
#19 0x00007fff8d16e7f5 in __CFRunLoopRun ()
#20 0x00007fff8d16e0e2 in CFRunLoopRunSpecific ()
#21 0x00007fff8cd6eeb4 in RunCurrentEventLoopInMode ()
#22 0x00007fff8cd6ec52 in ReceiveNextEventCommon ()
#23 0x00007fff8cd6eae3 in BlockUntilNextEventMatchingListInMode ()
#24 0x00007fff8846a563 in _DPSNextEvent ()
#25 0x00007fff88469e22 in -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] ()
#26 0x00007fff884611d3 in -[NSApplication run] ()
#27 0x000000010063da80 in QEventDispatcherMac::processEvents ()
#28 0x000000010036d114 in QEventLoop::processEvents ()
#29 0x000000010036d4c4 in QEventLoop::exec ()
#30 0x000000010036fbac in QCoreApplication::exec ()
#31 0x000000010000e483 in main (argc=1, argv=0x7fff5fbff9f0) at main.cpp:387
(gdb) 

```

**Comment by mlyle** [comment]
Closing these.  While there are still USB-related crashes in OSX, there has been substantial drift since 2013 and new traces should be gathered.
